#!/bin/bash

set -e

DB_NAME=$1
DB_USER=$2

if [[ -z $DB_NAME || -z $DB_USER ]]; then
	echo "Usage: $0 db_name db_user"
	exit 1
fi

BASE=$(dirname $(readlink -f $0))
source $BASE/config

passwd=$(pwgen -svB 16 1)

mysql << EOF
CREATE DATABASE $DB_NAME DEFAULT CHARSET UTF8;
GRANT ALL ON $DB_NAME.* TO $DB_USER@localhost IDENTIFIED BY '$passwd';
EOF

cat << EOF
Summary
-------

Database: $DB_NAME
Username: $DB_USER
Password: $passwd
EOF
